### ISSUE TITLE
Medaka compatibility

### ISSUE THREAD

**Issue by alegarritano** [liu-congcong/MetaDecoder#12]
Hello,

I am running MetaDecoder on some long-read datasets that I have and it seems that while it runs without any issues when using the assembly generated by Flye, but it fails to generate the seed for the polished assembly. 

The polishing was done using Medaka. Is MetaDecoder not compatible with the polished assembly? 

Thank you

This is the error message: 

metadecoder seed --threads 24 -f /Paratimea_ONT/Medaka/consensus.fasta -o consensus.metadecoder.seed
2023-07-17 08:17:28 -> Identifying protein sequences.
Traceback (most recent call last):
  File "/mypython3env_MetaDecoder/bin/metadecoder", line 220, in <module>
    metadecoder_seed.main(parameters)
  File "/mypython3env_MetaDecoder/lib/python3.10/site-packages/metadecoder/metadecoder_seed.py", line 59, in main
    run_fraggenescan(
  File "/mypython3env_MetaDecoder/lib/python3.10/site-packages/metadecoder/run_subprocess.py", line 26, in run_fraggenescan
    worker(
  File "/mypython3env_MetaDecoder/lib/python3.10/site-packages/metadecoder/run_subprocess.py", line 11, in worker
    assert not run(command, stdout = DEVNULL, stderr = DEVNULL).returncode, message
  File "/apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/python-3.10.8-pmtwsrrmcmrs6olvgx5xhepgh7gl5vro/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/python-3.10.8-pmtwsrrmcmrs6olvgx5xhepgh7gl5vro/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/apps/z_install_tree/linux-rocky8-ivybridge/gcc-12.2.0/python-3.10.8-pmtwsrrmcmrs6olvgx5xhepgh7gl5vro/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/mypython3env_MetaDecoder/lib/python3.10/site-packages/metadecoder/fraggenescan'

**Comment by liu-congcong** [comment]
Hi alegarritano,

Thank you for your feedback.

MetaDecoder can handle any FASTA format file. The logs show that you don't have enough permissions to run the built-in component fraggenescan, you can reinstall MetaDecoder and the program will fix all the permissions for you.
`pip3 install --force-reinstall https://github.com/liu-congcong/MetaDecoder/releases/download/v1.0.17/metadecoder-1.0.17-py3-none-any.whl`

Additionally, you can manually change the permissions of the necessary files:
`chmod 755 /mypython3env_MetaDecoder/lib/python3.10/site-packages/metadecoder/fraggenescan`
`chmod 755 /mypython3env_MetaDecoder/lib/python3.10/site-packages/metadecoder/hmmsearch`

Best,

Cong-Cong

**Comment by alegarritano** [comment]
Hi Cong,
Thanks for getting back to me. This is weird, because the software ran without any issues when using Flye's assembly. Regardless, we have decided not to use the polished assembly for the binning, so I will just close this thread. Thanks once again.
