### ISSUE TITLE
RuntimeWarning / ValueError when specifying smaller --min_sequence_length for subset of samples

### ISSUE THREAD

**Issue by acvill** [liu-congcong/MetaDecoder#2]
I have implemented MetaDecoder to cluster metaSPAdes contigs for 32 samples. Following [my workflow](https://github.com/liu-congcong/MetaDecoder/issues/1#issuecomment-1126236105), I get clusters for most of my samples. However, for a minority of my samples (2 of 32), MetaDecoder fails at the `cluster` step when a smaller `--min_sequence_length` is specified. The error goes away when I use the default parameters (`--min_sequence_length 2500`). 

### Input
```
metadecoder cluster \
  -f /workdir/metaspades/sample01/contigs.fasta \
  -c ../metadecoder.coverage \
  -s metadecoder.seed \
  -o sample01_metadecoder \
  --min_sequence_length 1000
```

### Output
```
metadecoder cluster -f /workdir/metaspades/sample01/contigs.fasta -c ../metadecoder.coverage -s metadecoder.seed -o sample01_metadecoder --min_sequence_length 1000
2022-05-13 13:06:43 -> Loading fasta file.
2022-05-13 13:06:44 -> Done.
2022-05-13 13:06:44 -> Loading coverage file.
2022-05-13 13:06:47 -> Done.
2022-05-13 13:06:47 -> Counting kmers of all sequences.
2022-05-13 13:06:52 -> Done.
2022-05-13 13:06:52 -> Loading seeds file.
2022-05-13 13:06:52 -> Done.
2022-05-13 13:06:52 -> Running the DPGMM algorithm to obtain clusters.
/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/metadecoder/dirichlet_process_gaussian_mixture.py:41: RuntimeWarning: invalid value encountered in true_divide
  kmeans_labels = kmeans.fit_predict((self.__x - self.__gaussian_prior_mu) / numpy.sqrt(numpy.diag(self.__wishart_prior_psi)))
Traceback (most recent call last):
  File "/home/miniconda3/envs/metadecoder/bin/metadecoder", line 246, in <module>
    metadecoder_cluster.main(parameters)
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/metadecoder/metadecoder_cluster.py", line 334, in main
    dpgmm.main()
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/metadecoder/dirichlet_process_gaussian_mixture.py", line 233, in main
    self.__initialize_multinomial_fai()
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/metadecoder/dirichlet_process_gaussian_mixture.py", line 41, in __initialize_multinomial_fai
    kmeans_labels = kmeans.fit_predict((self.__x - self.__gaussian_prior_mu) / numpy.sqrt(numpy.diag(self.__wishart_prior_psi)))
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1122, in fit_predict
    return self.fit(X, sample_weight=sample_weight).labels_
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 1030, in fit
    X = self._validate_data(X, accept_sparse='csr',
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/sklearn/base.py", line 420, in _validate_data
    X = check_array(X, **check_params)
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/sklearn/utils/validation.py", line 644, in check_array
    _assert_all_finite(array,
  File "/home/miniconda3/envs/metadecoder/lib/python3.8/site-packages/sklearn/utils/validation.py", line 96, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

This isn't a big issue as I can specify a larger `--min_sequence_length`, though I thought you'd like to know.

**Comment by liu-congcong** [comment]
This error indicates that some features have no variance. I guess this could be due to using the shared coverage file, there is a column with all zero data. But this is not enough to explain why it works with the default parameters.
Could you please send assembly, seed and coverage files to 740484166@qq.com?
Thank you very much!

**Comment by liu-congcong** [comment]
"This isn't a big issue as I can specify a larger --min_sequence_length, though I thought you'd like to know."
Thanks to this information, I might know why.
The metaSPAdes usually produce a lot of short contigs.
Using a shared coverage file may reduce the coverage of contigs because some reads may be aligned to other individual genome (all individual genomes are merged together). This may lead to a variance of 0 for some sequencing samples. Increasing the length threshold (--min_sequence_length) can filter out these short contigs, and it is highly recommended that you set this parameter to 2500 or higher, as the features of short contigs are unreliable.
I have updated to solve this problem, thanks for your suggestion.

**Comment by acvill** [comment]
> This error indicates that some features have no variance. I guess this could be due to using the shared coverage file, there is a column with all zero data.

> Increasing the length threshold (--min_sequence_length) can filter out these short contigs, and it is highly recommended that you set this parameter to 2500 or higher, as the features of short contigs are unreliable.

Thank you for this insight. It sounds like I need to do a better job of cleaning up the small sequences in the assembly before creating my alignments. Sadly, the assembly data isn't mine to share, but I will post an update here when I find a solution to my issue.

**Comment by liu-congcong** [comment]
You do not need to remove short contigs before creating the alignments, as long as use "--min_sequence_length" option to specify a higher threshold (e.g. 2500). Contigs in the coverage file that do not meet this threshold will not participate in the clustering process.
MetaDecoder v.1.0.10 has solved this problem by adding a small number to the variance to avoid it being equal to zero.
According to my research, filtering out short contigs with unreliable features usually has no negative impact on the final results.
Thank you very much for your feedback.
