### ISSUE TITLE
Error when running metadecoder

### ISSUE THREAD

**Issue by psj1997** [liu-congcong/MetaDecoder#6]
Hi,

Thanks for developing MetaDecoder. When I runing MetaDecoder, I had this error:

2022-08-24 15:27:36 -> DPGMM: 203 iterations have been finished (550 components).
2022-08-24 15:27:42 -> DPGMM: 204 iterations have been finished (550 components).
2022-08-24 15:27:43 -> Done.
2022-08-24 15:28:03 -> Running the kmer frequency and coverage models for clustering.
2022-08-24 15:28:03 -> 4.89% of the total sequences have been processed.
Process Process-100:
Traceback (most recent call last):
  File "/home1/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home1/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home1/anaconda3/lib/python3.8/site-packages/metadecoder/metadecoder_cluster.py", line 202, in run_models
    seeds = select_seed(
  File "/home1/anaconda3/lib/python3.8/site-packages/metadecoder/seed_selection.py", line 98, in select_seed
    spectral_predictions = spectral_clustering.fit_predict(scores)
  File "/home1/anaconda3/lib/python3.8/site-packages/sklearn/cluster/_spectral.py", line 657, in fit_predict
    return super().fit_predict(X, y)
  File "/home1/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 736, in fit_predict
    self.fit(X)
  File "/home1/anaconda3/lib/python3.8/site-packages/sklearn/cluster/_spectral.py", line 622, in fit
    self.labels_ = spectral_clustering(
  File "/home1/anaconda3/lib/python3.8/site-packages/sklearn/cluster/_spectral.py", line 300, in spectral_clustering
    maps = spectral_embedding(
  File "/home1/anaconda3/lib/python3.8/site-packages/sklearn/manifold/_spectral_embedding.py", line 369, in spectral_embedding
    _, diffusion_map = lobpcg(
  File "/home1/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/lobpcg/lobpcg.py", line 494, in lobpcg
    activeBlockVectorAR = A(activeBlockVectorR)
  File "/home1/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/interface.py", line 390, in __call__
    return self*x
  File "/home1/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/interface.py", line 393, in __mul__
    return self.dot(x)
  File "/home1/anaconda3/lib/python3.8/site-packages/scipy/sparse/linalg/interface.py", line 422, in dot
    raise ValueError('expected 1-d or 2-d array or matrix, got %r'
ValueError: expected 1-d or 2-d array or matrix, got array(None, dtype=object)

Thanks for your any suggestions.

Sincerely
Shaojun

**Comment by liu-congcong** [comment]
Thank you very much for using MetaDecoder.
I am sorry that you have trouble running MetaDecoder. It seems to be a bug in SpectralClustering (in Sklearn), I have also encountered it, MetaDecoder version 1.0.13 has bypassed this problem, please uninstall the old version and try the latest version.
pip3 uninstall metadecoder
pip3 install https://github.com/liu-congcong/MetaDecoder/releases/download/v1.0.13/metadecoder-1.0.13-py3-none-any.whl

**Comment by psj1997** [comment]
Thanks! I have runned successfully.
